import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'

function read(path) {
  assert.ok(existsSync(path), `Arquivo obrigatório ausente: ${path}`)
  return readFileSync(path, 'utf8')
}

const gradle = read('app/build.gradle.kts')
const backendPackage = read('backend/package.json')
const backendConfig = read('backend/src/config.ts')
const backendApplication = read('backend/src/application.ts')
const deployProduction = read('backend/scripts/deploy-production.mjs')
const deployCloudflare = read('scripts/deploy-cloudflare.mjs')
const wrangler = read('backend/wrangler.jsonc')
const migration = read('database/007_ponto_operation_idempotency.sql')
const readinessIndexes = read('database/008_release_readiness_indexes.sql')
const validateWorkflow = read('.github/workflows/validate.yml')
const releaseWorkflow = read('.github/workflows/build-release-unsigned.yml')
const reliability = read('backend/src/routes/reliability-routes.ts')
const telemetry = read('backend/src/routes/device-telemetry-routes.ts')
const maintenance = read('backend/src/maintenance.ts')
const cloudflare = read('backend/src/cloudflare.ts')
const envExample = read('.env.example')
const accessCodeUi = read('app/src/main/java/com/pontocafe/app/ui/AccessCodeScreen.kt')
const kioskUi = read('app/src/main/java/com/pontocafe/app/ui/PontoFlowHost.kt')
const manifest = read('app/src/main/AndroidManifest.xml')
const accessCodeRoutes = read('backend/src/routes/access-code-routes.ts')
const pontoRegistration = read('backend/src/ponto-registration.ts')
const accessCodeMigration = read('database/012_access_codes.sql')
const systemUi = read('app/src/main/java/com/pontocafe/app/ui/SystemDiagnosticsScreen.kt')

for (const doc of [
  'docs/RELEASE_1_0_CHECKLIST.md',
  'docs/DISASTER_RECOVERY.md',
  'docs/PRIVACIDADE_DADOS.md',
]) {
  assert.ok(existsSync(doc), `Documento de produção ausente: ${doc}`)
}

assert.match(gradle, /versionCode = 110/)
assert.match(gradle, /versionName = "1\.1\.0"/)
assert.match(gradle, /isMinifyEnabled = true/)
assert.match(gradle, /isShrinkResources = true/)
assert.match(gradle, /compileSdk = 36/)
assert.match(gradle, /targetSdk = 36/)
// Nenhum vestígio de reconhecimento facial pode voltar ao APK.
assert.doesNotMatch(gradle, /play-services-tflite/)
assert.doesNotMatch(gradle, /androidx\.camera/)
assert.doesNotMatch(gradle, /mlkit/)
assert.doesNotMatch(gradle, /facenet/i)
assert.doesNotMatch(manifest, /permission\.CAMERA/)

assert.match(backendPackage, /"version"\s*:\s*"1\.1\.0"/)
assert.match(backendApplication, /const API_VERSION = '1\.1\.0'/)
assert.match(backendApplication, /apiVersion: API_VERSION/)
assert.doesNotMatch(backendApplication, /apiVersion:\s*'0\.7\.0'/)
assert.match(deployProduction, /const expectedApiVersion = String\(backendPackage\.version/)
assert.match(deployProduction, /status\.apiVersion !== expectedApiVersion/)
assert.doesNotMatch(deployProduction, /status\.apiVersion !== '0\.7\.0'/)
assert.match(deployCloudflare, /const expectedApiVersion = String\(backendPackage\.version/)
assert.match(deployCloudflare, /status\.apiVersion !== expectedApiVersion/)
assert.match(deployCloudflare, /status\.latestAndroidVersion !== expectedAndroidVersion/)
assert.match(deployCloudflare, /status\.minimumAndroidVersion !== expectedMinimumAndroidVersion/)
assert.match(deployCloudflare, /\['--workspace', 'backend', 'run', 'validate'\]/)
assert.match(deployCloudflare, /\['run', 'release:check'\]/)
assert.match(deployCloudflare, /\['deploy', '--dry-run'\]/)
assert.match(deployCloudflare, /cwd: backendDir/)

assert.match(backendConfig, /ACCESS_CODE_TTL_SECONDS', 120/)
assert.match(backendConfig, /ACCESS_CODE_MAX_ATTEMPTS', 8/)
assert.match(backendConfig, /COFFEE_GRACE_SECONDS', 60/)
assert.doesNotMatch(backendConfig, /FACE_/)
assert.match(backendConfig, /PONTO_OPERATION_RETENTION_DAYS', 30/)
assert.match(backendConfig, /DEVICE_HEALTH_RETENTION_DAYS', 30/)
assert.match(backendConfig, /APP_LATEST_ANDROID_VERSION', '1\.1\.0'/)
assert.match(backendConfig, /APP_MIN_ANDROID_VERSION', '1\.1\.0'/)
assert.match(wrangler, /"ACCESS_CODE_TTL_SECONDS": "120"/)
assert.match(wrangler, /"COFFEE_GRACE_SECONDS": "60"/)
assert.doesNotMatch(wrangler, /FACE_/)
assert.match(wrangler, /"PONTO_OPERATION_RETENTION_DAYS": "30"/)
assert.match(wrangler, /"DEVICE_HEALTH_RETENTION_DAYS": "30"/)
assert.match(wrangler, /"APP_LATEST_ANDROID_VERSION": "1\.1\.0"/)
assert.match(wrangler, /"APP_MIN_ANDROID_VERSION": "1\.1\.0"/)

assert.match(migration, /create table if not exists operacoes_ponto_idempotentes/i)
assert.match(migration, /REGISTRO_RAPIDO/)
assert.match(accessCodeMigration, /create table if not exists codigos_acesso/i)
assert.match(accessCodeMigration, /drop table if exists templates_faciais/)
assert.match(accessCodeMigration, /drop table if exists verificacoes_faciais/)
assert.match(accessCodeMigration, /carencia_segundos/)
assert.match(accessCodeMigration, /ux_codigo_acesso_vivo/)
assert.match(migration, /INICIAR/)
assert.match(migration, /FINALIZAR/)
assert.match(readinessIndexes, /idx_operacoes_ponto_concluido_em/)
assert.match(readinessIndexes, /idx_auditoria_app_health_dispositivo_criado/)
assert.match(readinessIndexes, /idx_auditoria_app_health_criado/)
assert.match(readinessIndexes, /on auditoria \(criado_em\)/)
assert.match(readinessIndexes, /where acao='APP_HEALTH' and entidade='DISPOSITIVO'/)

assert.match(validateWorkflow, /npm --workspace backend run validate/)
assert.match(validateWorkflow, /npm run release:check/)
assert.match(validateWorkflow, /:app:testReleaseUnitTest :app:assembleRelease/)
assert.match(releaseWorkflow, /:app:testReleaseUnitTest :app:assembleRelease/)

assert.match(reliability, /operacoesProtegidasUltimas24h/)
assert.match(reliability, /comTelemetriaRecente/)
assert.match(reliability, /alertasSaude/)
assert.match(telemetry, /APP_HEALTH/)
assert.doesNotMatch(telemetry, /embedding/i)
assert.doesNotMatch(telemetry, /foto/i)
assert.doesNotMatch(telemetry, /senha/i)
assert.doesNotMatch(telemetry, /unlock.*pin/i)

assert.match(maintenance, /cleanupExpiredPontoOperations/)
assert.match(maintenance, /delete from operacoes_ponto_idempotentes/)
assert.match(maintenance, /cleanupExpiredDeviceHealthTelemetry/)
assert.match(maintenance, /acao in [(]'APP_HEALTH','DEVICE_HEARTBEAT'[)]/)
assert.match(cloudflare, /cleanupExpiredPontoOperations/)
assert.match(cloudflare, /cleanupExpiredDeviceHealthTelemetry/)
assert.match(envExample, /PONTO_OPERATION_RETENTION_DAYS=30/)
assert.match(envExample, /COFFEE_GRACE_SECONDS=60/)
assert.doesNotMatch(envExample, /FACE_/)
assert.match(envExample, /DEVICE_HEALTH_RETENTION_DAYS=30/)

// O passe vale uma saída e um retorno, e só serve para quem o recebeu.
assert.match(accessCodeRoutes, /ux_codigo_acesso_vivo/)
assert.match(accessCodeRoutes, /EM_PAUSA/)
assert.match(pontoRegistration, /secureCodeEquals/)
assert.match(pontoRegistration, /carencia_segundos/)
assert.match(kioskUi, /AccessCode\.LENGTH/)
assert.match(systemUi, /Integridade do Ponto/)
assert.match(systemUi, /Frota de dispositivos/)
assert.match(systemUi, /minimização de dados/)

console.log('PontoCafe 1.0 release contract: OK')
